// Command generate reads Bootstrap Icons SVG files and outputs a Go source file
// containing the icon data and named accessor functions.
//
// Usage:
//
//	go run ./contrib/bsicons/internal/generate -icons-dir /path/to/icons > contrib/bsicons/icons_generated.go
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

var innerSVGRe = regexp.MustCompile(`(?s)<svg[^>]*>(.*)</svg>`)

func main() {
	iconsDir := flag.String("icons-dir", "", "Path to the Bootstrap Icons SVG directory")
	flag.Parse()

	if *iconsDir == "" {
		log.Fatal("-icons-dir is required")
	}

	entries, err := os.ReadDir(*iconsDir)
	if err != nil {
		log.Fatalf("read icons dir: %v", err)
	}

	type iconEntry struct {
		Name     string // kebab-case name without .svg
		FuncName string // PascalCase Go function name
		Inner    string // inner SVG content
	}

	var icons []iconEntry

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".svg") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(*iconsDir, e.Name()))
		if err != nil {
			log.Fatalf("read %s: %v", e.Name(), err)
		}

		matches := innerSVGRe.FindSubmatch(data)
		if matches == nil {
			log.Fatalf("no <svg> found in %s", e.Name())
		}

		name := strings.TrimSuffix(e.Name(), ".svg")
		inner := strings.TrimSpace(string(matches[1]))

		icons = append(icons, iconEntry{
			Name:     name,
			FuncName: kebabToPascal(name),
			Inner:    inner,
		})
	}

	sort.Slice(icons, func(i, j int) bool {
		return icons[i].Name < icons[j].Name
	})

	// Output generated file.
	fmt.Println("// Code generated by go run ./contrib/bsicons/internal/generate; DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package bsicons")
	fmt.Println()
	fmt.Println("import \"github.com/a-h/templ\"")
	fmt.Println()

	// Named functions — each inlines its SVG data so the linker can
	// eliminate unused icons from the binary.
	for _, ic := range icons {
		fmt.Printf("// %s returns the %q Bootstrap Icon as a templ.Component.\n", ic.FuncName, ic.Name)
		fmt.Printf("func %s(class ...string) templ.Component { return icon(%q, class...) }\n\n", ic.FuncName, ic.Inner)
	}
}

// kebabToPascal converts a kebab-case string to PascalCase.
// Names starting with a digit are prefixed with "Nr".
func kebabToPascal(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		if r == '-' {
			upper = true
			continue
		}
		if upper {
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	result := b.String()
	if len(result) > 0 && unicode.IsDigit(rune(result[0])) {
		return "Nr" + result
	}
	return result
}
