repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: golangci-lint-mod
      - id: go-vulncheck-mod
      - id: go-test-mod
      - id: go-mod-tidy

  - repo: local
    hooks:
      - id: sass-theme
        name: Compile Bootstrap Sass theme
        entry: just sass
        language: system
        files: 'contrib/bootstrap/scss/.*\.scss$'
        pass_filenames: false

  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-golang
        types_or: [html]
