// Command hello is a minimal burrow application that serves a single
// "Hello, World!" page with Tailwind v4 styling and i18n support.
//
// This example demonstrates the core concepts of a burrow app in a
// flat layout — one Go file, one templates/ directory, one static/
// directory, one tailwind.css:
//
//   - Creating a server with contrib apps (staticfiles, htmx)
//   - Defining a custom app that ships its own templates and embeds
//     its own static CSS
//   - Configuring the CLI with urfave/cli for flags like --host, --port, etc.
//
// Translations are provided via burrow's built-in `t` template function.
//
// Run it (mise builds the Tailwind CSS first, then starts the server):
//
//	mise run example-hello
//
// Then open http://localhost:8080 in your browser.
package main

import (
	"context"
	"embed"
	"io/fs"
	"log"
	"net/http"
	"os"

	"github.com/go-chi/chi/v5"
	"github.com/oliverandrich/burrow"
	"github.com/oliverandrich/burrow/contrib/htmx"
	"github.com/oliverandrich/burrow/contrib/staticfiles"
	_ "github.com/oliverandrich/den/backend/sqlite" // register sqlite:// scheme
	"github.com/urfave/cli/v3"
)

//go:embed templates
var templateFS embed.FS

//go:embed translations
var translationFS embed.FS

// all:static so the placeholder .gitkeep is included; the real
// app.min.css is generated by `mise run example-hello` and lives
// alongside it (gitignored — see .gitignore).
//
//go:embed all:static
var staticFS embed.FS

func main() {
	// staticFS has files under `static/app.min.css`; fs.Sub strips that
	// directory so staticURL resolves names directly without an extra
	// `static/` segment.
	staticRoot, _ := fs.Sub(staticFS, "static")

	staticApp, err := staticfiles.New(staticRoot)
	if err != nil {
		log.Fatal(err)
	}

	srv := burrow.NewServer(
		staticApp,
		htmx.New(),
		&helloApp{},
	)
	srv.SetLayout("hello/layout")

	cmd := &cli.Command{
		Name:   "hello",
		Usage:  "Minimal burrow hello world application",
		Flags:  srv.Flags(nil),
		Action: srv.Run,
	}
	if err := cmd.Run(context.Background(), os.Args); err != nil {
		log.Fatal(err)
	}
}

// helloApp is a minimal Burrow app contributing one route, two
// templates (layout + page), and translations.
type helloApp struct{}

func (a *helloApp) Name() string         { return "hello" }
func (a *helloApp) TranslationFS() fs.FS { return translationFS }

func (a *helloApp) TemplateFS() fs.FS {
	sub, _ := fs.Sub(templateFS, "templates")
	return sub
}

func (a *helloApp) Routes(r chi.Router) {
	r.Get("/", burrow.Handle(func(w http.ResponseWriter, r *http.Request) error {
		return burrow.Render(w, r, http.StatusOK, "hello/home", map[string]any{
			"Title": "Hello",
		})
	}))
}
