package csrf

import (
	"html/template"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	gorillacsrf "github.com/gorilla/csrf"
	"github.com/oliverandrich/burrow"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Compile-time interface assertions.
var (
	_ burrow.App               = (*App)(nil)
	_ burrow.Configurable      = (*App)(nil)
	_ burrow.HasMiddleware     = (*App)(nil)
	_ burrow.HasRequestFuncMap = (*App)(nil)
)

func TestName(t *testing.T) {
	a := New()
	assert.Equal(t, "csrf", a.Name())
}

// newTestApp creates a configured App with a random key for testing.
func newTestApp(t *testing.T) *App {
	t.Helper()
	a := New()
	_ = a.Register(&burrow.AppConfig{
		Config: &burrow.Config{
			Server: burrow.ServerConfig{BaseURL: "http://localhost:8080"},
		},
	})
	require.NoError(t, a.configure("", false))
	return a
}

func TestCSRFTokenSetInContext(t *testing.T) {
	a := newTestApp(t)

	var token string
	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		token = Token(r.Context())
		w.WriteHeader(http.StatusOK)
	})

	mws := a.Middleware()
	require.Len(t, mws, 1)

	handler := mws[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusOK, rr.Code)
	assert.NotEmpty(t, token, "CSRF token should be set in context")
}

func TestCSRFRejectsPostWithoutToken(t *testing.T) {
	a := newTestApp(t)

	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})

	handler := a.Middleware()[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodPost, "/", strings.NewReader("data=value"))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusForbidden, rr.Code)
	body := rr.Body.String()
	assert.Equal(t, "Forbidden\n", body, "error response must not reveal CSRF failure reason")
}

func TestCSRFAcceptsPostWithToken(t *testing.T) {
	a := newTestApp(t)

	// First, do a GET to obtain the token and cookie.
	var token string
	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		token = gorillacsrf.Token(r)
		w.WriteHeader(http.StatusOK)
	})

	handler := a.Middleware()[0](inner)

	getReq := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	getRR := httptest.NewRecorder()
	handler.ServeHTTP(getRR, getReq)

	require.NotEmpty(t, token)

	// Extract cookies from GET response.
	cookies := getRR.Result().Cookies()

	// Now POST with the token in the header and the cookie.
	postReq := httptest.NewRequestWithContext(t.Context(), http.MethodPost, "/", strings.NewReader("data=value"))
	postReq.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	postReq.Header.Set("X-CSRF-Token", token)
	for _, c := range cookies {
		postReq.AddCookie(c)
	}

	postRR := httptest.NewRecorder()
	handler.ServeHTTP(postRR, postReq)

	assert.Equal(t, http.StatusOK, postRR.Code)
}

func TestCSRFAcceptsGet(t *testing.T) {
	a := newTestApp(t)

	called := false
	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		called = true
		w.WriteHeader(http.StatusOK)
	})

	handler := a.Middleware()[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.True(t, called)
	assert.Equal(t, http.StatusOK, rr.Code)
}

func TestAutoGeneratedKey(t *testing.T) {
	a := New()
	_ = a.Register(&burrow.AppConfig{
		Config: &burrow.Config{
			Server: burrow.ServerConfig{BaseURL: "http://localhost:8080"},
		},
	})

	// Empty key should auto-generate without error.
	err := a.configure("", false)
	require.NoError(t, err)
	assert.NotNil(t, a.protect, "protect middleware should be configured")
}

func TestExplicitKey(t *testing.T) {
	a := New()
	_ = a.Register(&burrow.AppConfig{
		Config: &burrow.Config{
			Server: burrow.ServerConfig{BaseURL: "https://example.com"},
		},
	})

	// Valid 32-byte hex key.
	key := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	err := a.configure(key, true)
	require.NoError(t, err)
	assert.NotNil(t, a.protect)
}

func TestInvalidKeyReturnsError(t *testing.T) {
	a := New()
	_ = a.Register(&burrow.AppConfig{
		Config: &burrow.Config{},
	})

	err := a.configure("not-hex", false)
	assert.Error(t, err)
}

func TestRequestFuncMap(t *testing.T) {
	a := newTestApp(t)

	var gotToken string
	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fm := a.RequestFuncMap(r)
		csrfTokenFunc := fm["csrfToken"].(func() string)
		gotToken = csrfTokenFunc()
		w.WriteHeader(http.StatusOK)
	})

	handler := a.Middleware()[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusOK, rr.Code)
	assert.NotEmpty(t, gotToken)
}

func TestRequestFuncMapCsrfField(t *testing.T) {
	a := newTestApp(t)

	var gotField template.HTML
	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fm := a.RequestFuncMap(r)
		csrfFieldFunc := fm["csrfField"].(func() template.HTML)
		gotField = csrfFieldFunc()
		w.WriteHeader(http.StatusOK)
	})

	handler := a.Middleware()[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusOK, rr.Code)
	assert.Contains(t, string(gotField), `<input type="hidden" name="gorilla.csrf.Token"`)
	assert.Contains(t, string(gotField), `value="`)
}

func TestSecureDerivedFromBaseURL(t *testing.T) {
	tests := []struct {
		baseURL string
		secure  bool
	}{
		{"https://example.com", true},
		{"http://localhost:8080", false},
		{"http://example.com", false},
		{"https://localhost", true},
	}

	for _, tt := range tests {
		t.Run(tt.baseURL, func(t *testing.T) {
			a := New()
			_ = a.Register(&burrow.AppConfig{
				Config: &burrow.Config{
					Server: burrow.ServerConfig{BaseURL: tt.baseURL},
				},
			})
			err := a.configure("", tt.secure)
			require.NoError(t, err)
			// Verify the middleware was created (indirect check).
			assert.NotNil(t, a.protect)
		})
	}
}
