package csrf

import (
	"context"
	"html/template"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	gorillacsrf "github.com/gorilla/csrf"
	"github.com/oliverandrich/burrow"
	"github.com/oliverandrich/burrow/registry"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/urfave/cli/v3"
)

// exemptStubApp is a test fixture: a minimal App that also implements
// ExemptPaths, so we can put it into a registry and verify the csrf
// middleware picks the paths up.
type exemptStubApp struct {
	name  string
	paths []string
}

func (s *exemptStubApp) Name() string              { return s.name }
func (s *exemptStubApp) CSRFExemptPaths() []string { return s.paths }

// newTestAppWithExempts builds a csrf app whose registry contains stub
// apps with the given exempt-path declarations. Each call to the
// function adds one stub app named "stub-<i>" with its paths.
func newTestAppWithExempts(t *testing.T, paths ...[]string) *App {
	t.Helper()
	reg := registry.New()
	for i, p := range paths {
		registry.Add(reg, &exemptStubApp{name: stubName(i), paths: p})
	}
	a := New()
	a.registry = reg
	require.NoError(t, a.configure("", false))
	return a
}

func stubName(i int) string {
	return "stub-" + string(rune('a'+i))
}

// Compile-time interface assertions.
var (
	_ burrow.App               = (*App)(nil)
	_ burrow.Configurable      = (*App)(nil)
	_ burrow.HasMiddleware     = (*App)(nil)
	_ burrow.HasRequestFuncMap = (*App)(nil)
)

func TestName(t *testing.T) {
	a := New()
	assert.Equal(t, "csrf", a.Name())
}

// newTestApp creates a configured App with a random key for testing.
func newTestApp(t *testing.T) *App {
	t.Helper()
	a := New()
	require.NoError(t, a.configure("", false))
	return a
}

func TestCSRFTokenSetInContext(t *testing.T) {
	a := newTestApp(t)

	var token string
	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		token = Token(r.Context())
		w.WriteHeader(http.StatusOK)
	})

	mws := a.Middleware()
	require.Len(t, mws, 1)

	handler := mws[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusOK, rr.Code)
	assert.NotEmpty(t, token, "CSRF token should be set in context")
}

func TestCSRFRejectsPostWithoutToken(t *testing.T) {
	a := newTestApp(t)

	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})

	handler := a.Middleware()[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodPost, "/", strings.NewReader("data=value"))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusForbidden, rr.Code)
	body := rr.Body.String()
	assert.Equal(t, "Forbidden\n", body, "error response must not reveal CSRF failure reason")
}

func TestCSRFAcceptsPostWithToken(t *testing.T) {
	a := newTestApp(t)

	// First, do a GET to obtain the token and cookie.
	var token string
	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		token = gorillacsrf.Token(r)
		w.WriteHeader(http.StatusOK)
	})

	handler := a.Middleware()[0](inner)

	getReq := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	getRR := httptest.NewRecorder()
	handler.ServeHTTP(getRR, getReq)

	require.NotEmpty(t, token)

	// Extract cookies from GET response.
	cookies := getRR.Result().Cookies()

	// Now POST with the token in the header and the cookie.
	postReq := httptest.NewRequestWithContext(t.Context(), http.MethodPost, "/", strings.NewReader("data=value"))
	postReq.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	postReq.Header.Set("X-CSRF-Token", token)
	for _, c := range cookies {
		postReq.AddCookie(c)
	}

	postRR := httptest.NewRecorder()
	handler.ServeHTTP(postRR, postReq)

	assert.Equal(t, http.StatusOK, postRR.Code)
}

func TestCSRFAcceptsGet(t *testing.T) {
	a := newTestApp(t)

	called := false
	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		called = true
		w.WriteHeader(http.StatusOK)
	})

	handler := a.Middleware()[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.True(t, called)
	assert.Equal(t, http.StatusOK, rr.Code)
}

func TestAutoGeneratedKey(t *testing.T) {
	a := New()

	// Empty key should auto-generate without error.
	err := a.configure("", false)
	require.NoError(t, err)
	assert.NotNil(t, a.protect, "protect middleware should be configured")
}

func TestExplicitKey(t *testing.T) {
	a := New()

	// Valid 32-byte hex key.
	key := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	err := a.configure(key, true)
	require.NoError(t, err)
	assert.NotNil(t, a.protect)
}

func TestInvalidKeyReturnsError(t *testing.T) {
	a := New()

	err := a.configure("not-hex", false)
	assert.Error(t, err)
}

func TestRequestFuncMap(t *testing.T) {
	a := newTestApp(t)

	var gotToken string
	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fm := a.RequestFuncMap(r.Context())
		csrfTokenFunc := fm["csrfToken"].(func() string)
		gotToken = csrfTokenFunc()
		w.WriteHeader(http.StatusOK)
	})

	handler := a.Middleware()[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusOK, rr.Code)
	assert.NotEmpty(t, gotToken)
}

func TestRequestFuncMapCsrfField(t *testing.T) {
	a := newTestApp(t)

	var gotField template.HTML
	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fm := a.RequestFuncMap(r.Context())
		csrfFieldFunc := fm["csrfField"].(func() template.HTML)
		gotField = csrfFieldFunc()
		w.WriteHeader(http.StatusOK)
	})

	handler := a.Middleware()[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusOK, rr.Code)
	assert.Contains(t, string(gotField), `<input type="hidden" name="gorilla.csrf.Token"`)
	assert.Contains(t, string(gotField), `value="`)
}

func TestRequestFuncMapCsrfHxHeaders(t *testing.T) {
	a := newTestApp(t)

	var gotAttr template.HTMLAttr
	inner := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fm := a.RequestFuncMap(r.Context())
		fn := fm["csrfHxHeaders"].(func() template.HTMLAttr)
		gotAttr = fn()
		w.WriteHeader(http.StatusOK)
	})

	handler := a.Middleware()[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusOK, rr.Code)
	assert.Contains(t, string(gotAttr), ` hx-headers='{"X-CSRF-Token":"`)
	assert.Contains(t, string(gotAttr), `"}'`)
}

func TestFlags(t *testing.T) {
	a := New()
	flags := a.Flags(nil)

	require.Len(t, flags, 1)
	assert.Equal(t, "csrf-key", flags[0].Names()[0])
}

func TestConfigureWithHTTPBaseURL(t *testing.T) {
	a := New()
	appCfg := &burrow.AppConfig{
		Config: &burrow.Config{
			Server: burrow.ServerConfig{BaseURL: "http://localhost:8080"},
		},
	}

	cliCmd := &cli.Command{
		Name:  "test",
		Flags: a.Flags(nil),
		Action: func(_ context.Context, cmd *cli.Command) error {
			return a.Configure(appCfg, cmd)
		},
	}

	err := cliCmd.Run(context.Background(), []string{"test"})
	require.NoError(t, err)
	assert.NotNil(t, a.protect)
	assert.False(t, a.secure)
}

func TestConfigureWithHTTPSBaseURL(t *testing.T) {
	a := New()
	appCfg := &burrow.AppConfig{
		Config: &burrow.Config{
			Server: burrow.ServerConfig{BaseURL: "https://example.com"},
		},
	}

	cliCmd := &cli.Command{
		Name:  "test",
		Flags: a.Flags(nil),
		Action: func(_ context.Context, cmd *cli.Command) error {
			return a.Configure(appCfg, cmd)
		},
	}

	err := cliCmd.Run(context.Background(), []string{"test"})
	require.NoError(t, err)
	assert.NotNil(t, a.protect)
	assert.True(t, a.secure)
}

func TestConfigureWithExplicitKey(t *testing.T) {
	a := New()
	appCfg := &burrow.AppConfig{
		Config: &burrow.Config{
			Server: burrow.ServerConfig{BaseURL: "http://localhost:8080"},
		},
	}

	key := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

	cliCmd := &cli.Command{
		Name:  "test",
		Flags: a.Flags(nil),
		Action: func(_ context.Context, cmd *cli.Command) error {
			return a.Configure(appCfg, cmd)
		},
	}

	err := cliCmd.Run(context.Background(), []string{"test", "--csrf-key", key})
	require.NoError(t, err)
	assert.NotNil(t, a.protect)
}

func TestConfigureWithInvalidKey(t *testing.T) {
	a := New()
	appCfg := &burrow.AppConfig{
		Config: &burrow.Config{
			Server: burrow.ServerConfig{BaseURL: "http://localhost:8080"},
		},
	}

	cliCmd := &cli.Command{
		Name:  "test",
		Flags: a.Flags(nil),
		Action: func(_ context.Context, cmd *cli.Command) error {
			return a.Configure(appCfg, cmd)
		},
	}

	err := cliCmd.Run(context.Background(), []string{"test", "--csrf-key", "not-hex"})
	assert.Error(t, err)
}

func TestConfigureWithNilConfig(t *testing.T) {
	a := New()
	appCfg := &burrow.AppConfig{}

	cliCmd := &cli.Command{
		Name:  "test",
		Flags: a.Flags(nil),
		Action: func(_ context.Context, cmd *cli.Command) error {
			return a.Configure(appCfg, cmd)
		},
	}

	err := cliCmd.Run(context.Background(), []string{"test"})
	require.NoError(t, err)
	assert.NotNil(t, a.protect)
	assert.False(t, a.secure, "secure should be false when config is nil")
}

func TestSecureDerivedFromBaseURL(t *testing.T) {
	tests := []struct {
		baseURL string
		secure  bool
	}{
		{"https://example.com", true},
		{"http://localhost:8080", false},
		{"http://example.com", false},
		{"https://localhost", true},
	}

	for _, tt := range tests {
		t.Run(tt.baseURL, func(t *testing.T) {
			a := New()
			err := a.configure("", tt.secure)
			require.NoError(t, err)
			// Verify the middleware was created (indirect check).
			assert.NotNil(t, a.protect)
		})
	}
}

// --- ExemptPaths ---

// postWithoutToken issues a POST to the given path and returns the recorder.
// Helper for the exempt-path tests; the only thing they care about is whether
// the response is 200 (exempted) or 403 (still enforced).
func postWithoutToken(t *testing.T, handler http.Handler, path string) *httptest.ResponseRecorder {
	t.Helper()
	req := httptest.NewRequestWithContext(t.Context(), http.MethodPost, path, strings.NewReader("data=value"))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)
	return rr
}

func TestExemptPaths_ExactMatchBypassesValidation(t *testing.T) {
	a := newTestAppWithExempts(t, []string{"/webmention"})
	inner := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusOK) })
	handler := a.Middleware()[0](inner)

	rr := postWithoutToken(t, handler, "/webmention")

	assert.Equal(t, http.StatusOK, rr.Code, "exact-path exempt must bypass CSRF check")
}

func TestExemptPaths_PrefixMatchBypassesValidation(t *testing.T) {
	a := newTestAppWithExempts(t, []string{"/inbox/"})
	inner := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusOK) })
	handler := a.Middleware()[0](inner)

	for _, path := range []string{"/inbox/alice", "/inbox/bob/feed"} {
		t.Run(path, func(t *testing.T) {
			rr := postWithoutToken(t, handler, path)
			assert.Equal(t, http.StatusOK, rr.Code, "prefix exempt %q must match %q", "/inbox/", path)
		})
	}
}

func TestExemptPaths_DoesNotMatchUnrelatedPath(t *testing.T) {
	a := newTestAppWithExempts(t, []string{"/webmention"})
	inner := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusOK) })
	handler := a.Middleware()[0](inner)

	rr := postWithoutToken(t, handler, "/other")

	assert.Equal(t, http.StatusForbidden, rr.Code, "non-exempt paths must still require a CSRF token")
}

func TestExemptPaths_ExactDoesNotMatchSubpath(t *testing.T) {
	a := newTestAppWithExempts(t, []string{"/webmention"})
	inner := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusOK) })
	handler := a.Middleware()[0](inner)

	rr := postWithoutToken(t, handler, "/webmention/extra")

	assert.Equal(t, http.StatusForbidden, rr.Code,
		"exact entry (no trailing slash) must not match descendant paths")
}

func TestExemptPaths_MergedAcrossMultipleApps(t *testing.T) {
	a := newTestAppWithExempts(t,
		[]string{"/webmention"},
		[]string{"/inbox/"},
	)
	inner := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusOK) })
	handler := a.Middleware()[0](inner)

	for _, path := range []string{"/webmention", "/inbox/alice"} {
		t.Run(path, func(t *testing.T) {
			rr := postWithoutToken(t, handler, path)
			assert.Equal(t, http.StatusOK, rr.Code)
		})
	}
}

func TestExemptPaths_NoProviderAppsLeavesBehaviourUnchanged(t *testing.T) {
	// Registry exists but no app implements ExemptPaths.
	a := newTestAppWithExempts(t)
	inner := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusOK) })
	handler := a.Middleware()[0](inner)

	rr := postWithoutToken(t, handler, "/anything")

	assert.Equal(t, http.StatusForbidden, rr.Code)
}

func TestExemptPaths_NilRegistryIsSafe(t *testing.T) {
	// newTestApp (used elsewhere) does not set a registry — this guards
	// against a nil-pointer panic in the matcher build path.
	a := newTestApp(t)
	inner := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusOK) })
	handler := a.Middleware()[0](inner)

	rr := postWithoutToken(t, handler, "/anything")

	assert.Equal(t, http.StatusForbidden, rr.Code,
		"a csrf app without a registry must still enforce CSRF (no panic, no silent bypass)")
}

func TestExemptPaths_GetOnExemptPathStillSucceeds(t *testing.T) {
	// Sanity check: exempting a path doesn't break ordinary GETs (which
	// were already accepted by csrf because GET isn't state-changing).
	a := newTestAppWithExempts(t, []string{"/webmention"})
	inner := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusOK) })
	handler := a.Middleware()[0](inner)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/webmention", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusOK, rr.Code)
}
