#!/usr/bin/env bash
#MISE description="Build documentation site (regenerates llms-full.txt and license listing first)"
set -euo pipefail

mise run licenses
cp CHANGELOG.md docs/changelog.md
cp THIRD_PARTY_LICENSES.md docs/third-party-licenses.md
mise run generate-llms-full
zensical build
